services:
  nextjs:
    command: npm run dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./data/warcraftData.db
