version: '3.8'

services:
  nextjs:
    command: npm run dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wowdb?schema=public
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
